# Generated by Django 4.0.2 on 2022-02-18 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ToDoList',
            new_name='FormAppModel',
        ),
    ]
